plugins {
	id "org.jetbrains.kotlin.jvm"
    id "com.gradleup.shadow"
	id "maven-publish"
	id "fabric-loom" version "1.14.6"
}

base {
	archivesName = "iwtcms-${minecraft_version}-fabric"
}

configurations {
	shadow
}

repositories {
    maven {
        name "luck-repo"
        url "https://repo.lucko.me/"
        content {
            includeModule "me.lucko", "spark-api"
        }
    }
}

dependencies {
	implementation shadow(project(":server"))

    // * Fabric
	minecraft "com.mojang:minecraft:$minecraft_version"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:$loader_version"
	modImplementation "net.fabricmc.fabric-api:fabric-api:$fabric_api_version"
	modImplementation "net.fabricmc:fabric-language-kotlin:$fabric_kotlin_version"
    // * Fabric
}

processResources {
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

shadowJar {
	minimize()
	configurations = [project.configurations.shadow]
}

loom {
	runs {
		remove client
	}
}