# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
kotlin.daemon.jvmargs=-Xmx4G

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.10
fabric_version=0.119.2+1.21.4
fabric_kotlin_version=1.13.0+kotlin.2.1.0

# Mod Properties
mod_version=2.0
maven_group=ua.pp.lumivoid.iwtcms
archives_base_name=iwtcms

# Dependencies
# https://ktor.io/docs/server-dependencies.html
ktor_version=3.0.1
# https://mvnrepository.com/artifact/io.netty/netty-all
netty_version=4.1.114.Final
# https://github.com/lightbend/config
hocon_config_version=1.4.3
# https://mvnrepository.com/artifact/commons-codec/commons-codec
commons_codec=1.18.0
# https://github.com/charleskorn/kaml/releases/latest
kaml_version=0.72.0
# https://spark.lucko.me/docs/Developer-API
spark_api_version=0.1-SNAPSHOT

# Uploadings
id_main=qOd1bFdY
id_fabric_api=P7dR8mSH
id_fabric_kotlin=Ha28R6CL
id_spark=l6YH9Als

release_type=release
release_minecraft_versions=["1.21.1", "1.21", "1.21.3", "1.21.2"]
