auth {
  // useAuthentication: enabling password for clients, client can't receive/send messages from/to server before login. By default it's enabled
  // DO NOT DISABLE IF YOU DON'T KNOW WHAT YOU DOING, IT CAUSE SECURITY ISSUES AND ANY, REPEAT, ANY PLAYER CAN GET ACCESS TO CONSOLE/FILES/SETTINGS AND OTHER
  use Authentication = true

  // needs ONLY IF useAuthentication enabled
  // here you can configure users
  // you can add custom users or remove existing
  users : [
    {
      // anonymous
      name : anonymous // do not remove if you wanna keep permits for anonymous
      // password : anonymous // doesn't matter
      permits : {
        read real time logs : false
        read logs history : false
        execute commands : false
        access to server stats : false
        read iwtcms config : false
        edit iwtcms config : false
        read minecraft server config : false
        edit minecraft server config : false
        kick players : false
        ban players : false
      }
    }
    {
      // admin
      name : admin
      password : iwtcms
      permits : {
        read real time logs : true
        read logs history : true
        execute commands : true
        access to server stats : true
        read iwtcms config : true
        edit iwtcms config : true
        read minecraft server config : true
        edit minecraft server config : true
        kick players : true
        ban players : true
      }
    }
    {
      // guest
      name : guest
      password : guest
      permits : {
        read real time logs : true
        read logs history : false
        execute commands : false
        access to server stats : true
        read iwtcms config : true
        edit iwtcms config : false
        read minecraft server config : true
        edit minecraft server config : false
        kick players : false
        ban players : false
      }
    }
  ]
}