auth {
  # useAuthentication: enabling password for clients, client can't receive/send messages from/to server before login. By default it's enabled
  # DO NOT DISABLE IF YOU DON'T KNOW WHAT YOU DOING, IT CAUSE SECURITY ISSUES AND ANY, REPEAT, ANY PLAYER CAN GET ACCESS TO CONSOLE/FILES/SETTINGS AND OTHER
  use Authentication = true // boolean

  # needs ONLY IF useAuthentication enabled
  # here you can configure users
  # you can add custom users or remove existing
  users : [ // list
    {
      # anonymous
      name : anonymous // string # do not remove if you wanna keep permits for anonymous
      # password : anonymous # doesn't matter
      permits : {
        read real time logs : false // boolean
        read logs history : false // boolean
        execute commands : false // boolean
        access to server stats : false // boolean
        read iwtcms config : false // boolean
        edit iwtcms config : false // boolean
        read minecraft server config : false // boolean
        edit minecraft server config : false // boolean
        kick players : false // boolean
        ban players : false // boolean
      }
    }
    {
      # admin
      name : admin // string
      password : iwtcms // string
      permits : {
        read real time logs : true // boolean
        read logs history : true // boolean
        execute commands : true // boolean
        access to server stats : true // boolean
        read iwtcms config : true // boolean
        edit iwtcms config : true // boolean
        read minecraft server config : true // boolean
        edit minecraft server config : true // boolean
        kick players : true // boolean
        ban players : true // boolean
      }
    }
    {
      # guest
      name : guest // string
      password : guest // string
      permits : {
        read real time logs : true // boolean
        read logs history : false // boolean
        execute commands : false // boolean
        access to server stats : true // boolean
        read iwtcms config : true // boolean
        edit iwtcms config : false // boolean
        read minecraft server config : true // boolean
        edit minecraft server config : false // boolean
        kick players : false // boolean
        ban players : false // boolean
      }
    }
  ]
}