server {
  // ip: address of IWTCMS embedded server. By default it's 127.0.0.1 (localhost)
  ip = "127.0.0.1"
  // port: any free port (DONT USE 25565). By default it's 25566
  port = 25566

  // logLevel: how much logs you get in client. can be TRACE, DEBUG, INFO, WARN, ERROR. By default it's INFO
  log Level = "INFO"

  database user = "iwtcms"
  database password = "iwtcms"
}

// read more about setting ssl here: https://modrinth.com/mod/i-want-to-control-my-server
ssl {
  // use SSL: enabling SSL for embedded server, clients must connect with SSL or they can't send/receive any data. By default it's enabled.
  // You must to know that if it disabled YOUR DATA CAN BE STOLEN (as passwords/files/settings/other)
  use SSL = true
  // custom Sertificate: if enabled IWTCMS won't generating new sertificate, instead it reads sertificates from config/iwtcms/keystore.jks
  custom Certificate = false
  // Actually idk what do this shit, but alias must be entered here. Usually you use it for custom generated certificates. By default it's "iwtcms". You can read more here: https://security.stackexchange.com/questions/123944/what-is-the-purpose-role-of-the-alias-attribute-in-java-keystore-files
  ssl Alias = "iwtcms"
  // sslPass: password for certificates, certs will be automaticly generated with this password or if you use any other certificates it will use pass to read it.
  ssl Pass = "keystorePassword"
}

stuff {
  // statistics period: period between each statistics data send, sets in millis. By default it's 1000
  statistics period = 1000
}

web {
  // enable IWTCMS control panel: enables cutie web interface with different features
  enable IWTCMS control panel = true
  // auto open IWTCMS page on startup: opens default webbrowser when server started
  auto open IWTCMS page on startup = false
}

dev {
  // used for developing, DO NOT CHANGE IF YOU ARE NO DEVELOPER
  // CAN CAUSES CRASH IF YOU USE COMPILED JAR
  // ENABLE IT IF YOU KNOW WHAT YOU DO
  // to know more read README.md on github or modrinth of IWTCMS
  dev mode = false
  auto open vite = false
  enable h2 web server = false
  use external h2 db = false
  external h2 db ip = localhost
  external h2 db port = 9092
}