# Available Configs
# All of these configs will be available in the iwtcms control panel

# example:
# any_name:
#   selector_name: any.conf # name of button which will be used in selector and also in url
#   config_name: this is any config # name of config displayed on top of settings tab
#   config_type: hocon # hocon, yaml, json, other (if other will be used you need custom reader (read documentation))
#   config_path: /path/to/config/any.conf # path to config starts from server root
#   make_backup: true # make backup of config before changes

minecraft_properties:
    selector_name: "server.properties"
    config_name: "Minecraft Server Properties"
    config_type: "minecraft" # custom reader
    config_path: "/server.properties"
    make_backup: "true"

iwtcms_config:
    selector_name: "iwtcms.conf"
    config_name: "I-Want-To-Control-My-Server Config"
    config_type: "hocon"
    config_path: "/iwtcms/iwtcms.conf"
    make_backup: "true"
