# https://ktor.io/docs/server-dependencies.html
ktor_version=3.4.0
# https://github.com/lightbend/config
hocon_config_version=1.4.5
# https://mvnrepository.com/artifact/commons-codec/commons-codec
commons_codec=1.21.0
# https://github.com/charleskorn/kaml/releases/latest
kaml_version=0.104.0

# https://spark.lucko.me/docs/Developer-API
spark_api_version=0.1-SNAPSHOT
# https://github.com/Kotlin/kotlinx-datetime?tab=readme-ov-file#using-in-your-projects
kotlinx_datetime_version=0.7.1

# https://www.jetbrains.com/help/exposed/exposed-modules.html
exposed_version=1.0.0

# https://mvnrepository.com/artifact/com.h2database/h2
h2_database_version=2.4.240
# https://mvnrepository.com/artifact/com.oracle.database.jdbc/ojdbc11
oracle_database_version=23.26.0.0.0
# https://mvnrepository.com/artifact/org.mariadb.jdbc/mariadb-java-client
mariadb_database_version=3.5.7
# https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc
mssql_database_version=13.3.1.jre11-preview
# https://mvnrepository.com/artifact/com.mysql/mysql-connector-j
mysql_database_version=9.5.0
# https://mvnrepository.com/artifact/org.postgresql/postgresql
postgresql_database_version=42.7.9

# https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api
log4j_version=2.25.3
# https://mvnrepository.com/artifact/org.slf4j/slf4j-api
slf4j_version=2.0.17
# https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-engine
junit_version=6.1.0-M1

