<script lang="ts">
    import {type AvailableConfigs} from "./configsManager";
    import Constants from "../../constants";
    import ToastSystem from "../../toastSystem";
    import DevMenu from "./DevMenu.svelte";
    import {onMount} from "svelte";
    import YAML from "yaml";
    import Selector from "./Selector.svelte";
    import Tab from "./Tab.svelte";

    let tabsContainer: HTMLDivElement;
    let configs: AvailableConfigs;
    let tabs: Tab[] = [];

    onMount(() => {
        try {
            fetch(Constants.CONFIG_URL).then(async (response) => (configs = YAML.parse(await response.text())));
        } catch (error) {
            ToastSystem.addToQueue(`Error: ${error}`, ToastSystem.ToastType.ERROR);
        }
    });
    // TODO: forbidden message
</script>

<div>
    <h1 class="flex content-center justify-center text-[36px]">Settings</h1>
    <div class="page-container relative flex items-center justify-center">
        <span class="absolute top-[-25px] left-[-80px] z-[2] w-[400px] transform-[rotate(-30deg)] bg-[red] px-[80px] text-[12px]">
            Note! "Easy mode" still in beta!<br />Please, be careful, make backups and report if something gone wrong!
        </span>

        {#if configs}
            {#if tabsContainer}
                <Selector tabsContainer={tabsContainer} configs={configs} tabs={tabs} />
            {/if}

            <div class="settings-tab-tabs mt-[80px] w-full overflow-x-hidden overflow-y-auto" style="height: calc(100% - 80px);" bind:this={tabsContainer}>
                <!-- * Content will be auto generated by js -->
                {#each Object.values(configs) as config, i}
                    <Tab selfConfigSetting={config} bind:this={tabs[i]}></Tab>
                {/each}
            </div>
        {/if}

        <DevMenu />
    </div>
</div>

<style lang="scss">
    @use "../../../styles/scrollbar";
    @use "../../../styles/variables";

    .settings-tab-tabs {
        @include scrollbar.scrollbar();
    }
</style>
