<div id="console-tab" class="tab" style="display: block; /* DEFAULT TAB */">
    <!-- ! DEFAULT TAB -->
    <div class="container">
        <h1>Console</h1>
        <div class="windows">
            <div class="statistics">
                <h3>Statistics</h3>
                <div class="cpu-load">
                    <span>CPU: </span>
                    <span class="value">none</span>
                </div>
                <div class="ram-usage">
                    <span>RAM: </span>
                    <span class="value">none</span>
                </div>
                <div class="uptime">
                    <span>Uptime: </span>
                    <span class="value">none</span>
                </div>
                <div class="players">
                    <span>Players: </span>
                    <span class="value">none</span>
                    <span>/</span>
                    <span class="max">none</span>
                </div>
                <div class="ip-addr">
                    <span>IP: </span>
                    <span class="value spoiler">none</span>
                </div>
                <div class="tps">
                    <span>TPS: </span>
                    <span class="value">none</span>
                </div>
                <div class="server-time">
                    <span>Server time: </span>
                    <span class="value">none</span>
                </div>
            </div>
            <div class="console">
                <div class="console-text">
                    <!-- * Content will be auto generated by js -->
                </div>
                <div class="total-messages">
                    <span>Total messages: </span>
                    <span class="count">
                        <!-- * Content will be auto generated by js -->
                    </span>
                </div>
                <div class="input disabled">
                    <span class="material-symbols-rounded"
                        >keyboard_arrow_right</span
                    >
                    <input class="input-field" type="text" placeholder="help" />
                </div>
            </div>
        </div>
    </div>
</div>
