modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Bumer-32/I-Want-To-Control-My-Server/issues"
license = "Apache-2.0"

[[mods]]
modId = "iwtcms"
version = "${version}"
displayName = "I Want To Control My Server"
authors = "Bumer_32"
description = '''
Allows you to control server through web!
'''
logoFile = "assets/iwtcms/icon.png"

[[dependencies.iwtcms]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iwtcms]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iwtcms]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "iwtcms.mixins.json"
