<script lang="ts">
    let consoleScroll: HTMLDivElement;
    let totalMessages: HTMLSpanElement;
    let messageFieldDiv: HTMLDivElement;
    let messageFieldInput: HTMLInputElement;
</script>

<div class="console transition-[background-color ease 0.3s] relative mr-[60px] ml-[25px] flex h-[90%] max-w-[1200px] flex-col content-center rounded-[10px] bg-[var(--console-background-color)]">
    <div class="console-text w-[calc(100% - 32px)] absolute top-[8px] flex flex-col overflow-x-hidden overflow-y-auto scroll-smooth" bind:this={consoleScroll}>
        <!-- * Content will be auto generated by js -->
    </div>
    <div class="total-messages absolute right-[35px] text-[12px]">
        <span>Total messages: </span>
        <span class="count" bind:this={totalMessages}>
            <!-- * Content will be auto generated by js -->
            0
        </span>
    </div>
    <div class="input disabled absolute bottom-0 left-0 flex w-full items-center" bind:this={messageFieldDiv}>
        <span class="material-symbols-rounded">keyboard_arrow_right</span>
        <input class="transition-[color ease 0.3s] w-full border-none bg-transparent focus:outline-none" type="text" placeholder="help" bind:this={messageFieldInput} />
    </div>
</div>

<style lang="scss">
    @use "../../../styles/variables";
    @use "../../../styles/scrollbar";
    @use "../../../styles/forbidden";

    .console {
        width: variables.$console-width;

        @include scrollbar.scrollbar;
        @include forbidden.forbidden(423px);

        .console-text {
            height: calc(100% - #{variables.$console-input-height} - 24px);
        }

        .total-messages {
            bottom: variables.$console-input-height;
        }

        .input input {
            height: variables.$console-input-height;
            color: var(--console-text-color);
        }
    }
</style>
