<script lang="ts"></script>

<div class="console">
    <div class="console-text" bind:this={consoleScroll}>
        <!-- * Content will be auto generated by js -->
    </div>
    <div class="total-messages">
        <span>Total messages: </span>
        <span class="count" bind:this={totalMessages}>
            <!-- * Content will be auto generated by js -->
            0
        </span>
    </div>
    <div class="input disabled" bind:this={messageFieldDiv}>
        <span class="material-symbols-rounded">keyboard_arrow_right</span>
        <input class="input-field" type="text" placeholder="help" bind:this={messageFieldInput} />
    </div>
</div>

<style lang="scss"></style>